#!/bin/bash -e

LLVM_DEFAULT_FLAGS="-O3"
program="${1:?missing program path}"
out="${2:?missing out path}"
llvm_flags="${3:-$LLVM_DEFAULT_FLAGS}"
nebula_flags="$4"

mkdir -p build
./nebula llvm $nebula_flags "$program" > "$out.ll"
clang $llvm_flags -S -emit-llvm -o build/ext.ll ir/codegen/ext/ext.c
llvm-link -o "$out.o" "$out.ll" build/ext.ll
llc $llvm_flags "$out.o"
clang $llvm_flags -o "$out" "$out.o.s"
