#!/bin/bash

program="$1"
out="$2"

mkdir -p build &&
./nebula "$program" llvm > "$out.ll" &&
clang -S -emit-llvm -o build/ext.ll codegen/ext/ext.c &&
llvm-link -o "$out.o" "$out.ll" build/ext.ll &&
llc "$out.o" &&
clang -o "$out" "$out.o.s"
