<program> ::= <instruction> <program> | epsilon

<instruction> ::= <space-space> <number>
                | <space-lf> <space>
                | <copy> <number>
                | <space-lf> <tab>
                | <space-lf> <lf>
                | <slide> <number>
                | <tab-space> <space-space>
                | <tab-space> <space-tab>
                | <tab-space> <space-lf>
                | <tab-space> <tab-space>
                | <tab-space> <tab-tab>
                | <tab-tab> <space>
                | <tab-tab> <tab>
                | <label> <number>
                | <call> <number>
                | <jmp> <number>
                | <jz> <number>
                | <jn> <number>
                | <lf-tab> <lf>
                | <lf-lf> <lf>
                | <tab-lf> <space-space>
                | <tab-lf> <space-tab>
                | <tab-lf> <tab-space>
                | <tab-lf> <tab-tab>

<space-space> ::= <space> <space>
<space-tab>   ::= <space> <tab>
<space-lf>    ::= <space> <lf>
<tab-space>   ::= <tab> <space>
<tab-tab>     ::= <tab> <tab>
<tab-lf>      ::= <tab> <lf>
<lf-space>    ::= <lf> <space>
<lf-tab>      ::= <lf> <tab>
<lf-lf>       ::= <lf> <lf>

<copy>  ::= <space> <tab-space>
<slide> ::= <space> <tab-lf>
<label> ::= <lf> <space-space>
<call>  ::= <lf> <space-tab>
<jmp>   ::= <lf> <space-lf>
<jz>    ::= <lf> <tab-space>
<jn>    ::= <lf> <tab-tab>

<number> ::= <space> <number>
           | <tab> <number>
           | "\n"

<space> ::= " "
<tab>   ::= "\t"
<lf>    ::= "\n"
